In [0]:
import pandas as pd
import numpy as np
d = pd.read_csv('CompanyJ_Twitterposts.csv')
d.head()

,Username,Followers,Created Time,Message,Character Count,Retweet Count,Like Count,Total Actions,Total Actions % Followers,Public Clicks,Type
0,Company J,8271550,2019-01-01T01:01:30,The New Yearâ€™s Party we want to see ðŸŽ‰ https://...,60-80,1169,4512,5681,0.068681,0,video
1,Company J,8271550,2019-01-01T01:06:27,This kid couldnâ€™t believe how close he was to ...,80-100,1675,14857,16532,0.199866,0,video
2,Company J,8271550,2019-01-01T01:09:08,Rockets ball movement ðŸ”¥ https://t.co/Tmrn2sG4A4,40-60,656,3554,4210,0.050897,0,video
3,Company J,8271550,2019-01-01T01:35:43,Jerami Grant. Oh man. https://t.co/RiUzkeL22O,40-60,1068,6986,8054,0.097370,0,video
4,Company J,8271550,2019-01-01T01:56:26,James Harden joins Kobe Bryant and MJ as the 3...,160-180,4555,15092,19647,0.237525,0,photo

In [0]:
d.drop(['Followers','Total Actions % Followers','Created Time', 'Public Clicks'] , axis =1, inplace= True )
d.head()

,Username,Message,Character Count,Retweet Count,Like Count,Total Actions,Type
0,Company J,The New Yearâ€™s Party we want to see ðŸŽ‰ https://...,60-80,1169,4512,5681,video
1,Company J,This kid couldnâ€™t believe how close he was to ...,80-100,1675,14857,16532,video
2,Company J,Rockets ball movement ðŸ”¥ https://t.co/Tmrn2sG4A4,40-60,656,3554,4210,video
3,Company J,Jerami Grant. Oh man. https://t.co/RiUzkeL22O,40-60,1068,6986,8054,video
4,Company J,James Harden joins Kobe Bryant and MJ as the 3...,160-180,4555,15092,19647,photo

In [0]:
df_null = pd.DataFrame({'Count': d.isnull().sum(), 'Percent': 100*d.isnull().sum()/len(d)})

df_null[df_null['Count'] > 0].sort_values(by=['Percent'], ascending=False)

Empty DataFrame
Columns: [Count, Percent]
Index: []

In [0]:
import re
message=[]
for msg in d.Message:
    x = re.sub(r'http\S+', '', msg)
    message.append(x)
d['Message'] = message
d.head()

,Username,Message,Character Count,Retweet Count,Like Count,Total Actions,Type
0,Company J,The New Yearâ€™s Party we want to see ðŸŽ‰,60-80,1169,4512,5681,video
1,Company J,This kid couldnâ€™t believe how close he was to ...,80-100,1675,14857,16532,video
2,Company J,Rockets ball movement ðŸ”¥,40-60,656,3554,4210,video
3,Company J,Jerami Grant. Oh man.,40-60,1068,6986,8054,video
4,Company J,James Harden joins Kobe Bryant and MJ as the 3...,160-180,4555,15092,19647,photo

In [0]:
message=[]
for msg in d.Message:
    x = re.sub(r'\W+', ' ', msg)
    message.append(x)
d['Message'] = message
d.head()

,Username,Message,Character Count,Retweet Count,Like Count,Total Actions,Type
0,Company J,The New Year s Party we want to see,60-80,1169,4512,5681,video
1,Company J,This kid couldn t believe how close he was to ...,80-100,1675,14857,16532,video
2,Company J,Rockets ball movement,40-60,656,3554,4210,video
3,Company J,Jerami Grant Oh man,40-60,1068,6986,8054,video
4,Company J,James Harden joins Kobe Bryant and MJ as the 3...,160-180,4555,15092,19647,photo

In [0]:
tweetcount = []
for msg in d.Message:
    x = len(msg)
    tweetcount.append(x)
d['Character Count'] = tweetcount
d.head()

,Username,Message,Character Count,Retweet Count,Like Count,Total Actions,Type
0,Company J,The New Year s Party we want to see,36,1169,4512,5681,video
1,Company J,This kid couldn t believe how close he was to ...,60,1675,14857,16532,video
2,Company J,Rockets ball movement,22,656,3554,4210,video
3,Company J,Jerami Grant Oh man,20,1068,6986,8054,video
4,Company J,James Harden joins Kobe Bryant and MJ as the 3...,142,4555,15092,19647,photo

In [0]:
d.to_csv(r'A:/OPIM5671-Prof.JingPeng/Project/twitter_new.csv', index = False)